# Generated by Django 4.0 on 2021-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID пользователя в telegram')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('last_name', models.TextField(verbose_name='Фамилия пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользоватеkя телеграмм',
            },
        ),
    ]
